server:
  port: 10001

spring:
  application:
    name: member-service-provider-10000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud_DB
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml # 指定 mapper.xml文件位置
  type-aliases-package: com.springcloud.entity # 实例类所在的包，这样通过类名可以引用