server:
  port: 10006

spring:
  application:
    name: member-service-nacos-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud_DB
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置 Nacos 地址
# 暴露所有监控点
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: classpath:mapper/*.xml # 指定 mapper.xml文件位置
  type-aliases-package: com.springcloud.entity # 实例类所在的包，这样通过类名可以引用
