server:
  port: 9002

eureka:
  instance:
    hostname: eureka9002.com # 服务实例名
  client:
    # 配置不向注册中心注册自己
    register-with-eureka: false
    # 表示自己就是注册中心，作用就是维护注册服务实例，不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与 eureka server 交互模块，查询服务和注册服务都需要依赖这个地址
      # defaultZone: http://localhost:9001/eureka
      # 相互注册
      defaultZone: http://eureka9001.com:9001/eureka