server:
  port: 20000
spring:
  application:
    name: e-commerce-gateway-20000
  cloud:
    gateway:
      routes: # 配置路由，可以配置多个路由 List<RouteDefinition> routes
        - id: member_router01 # 路由的 ID，程序员自己写，要求唯一
          # gateway 最终访问的 url 是 url = uri + Path
          # 匹配后提供服务的路由地址：也可以是外网 http://baidu.com
          # 比如：客户端/浏览器请求 url http://localhost:20000/member/get/1
          # 如果根据 Path 匹配成功 最终访问的 url/转发url 就是url=http://localhost:10000/member/get/1
          # 如果匹配失败，gateway 返回 404信息
          #疑问: 这里配置的 uri 是固定,在当前这种情况其实可以没有有Eureka Server,后面会使用灵活方式
          #     配置，就会使用到Eureka Server
          uri: http://localhost:10000
          predicates: # 断言，路径相匹配的进行路由
            - Path=/member/get/**
eureka:
  instance:
    hostname: e-commerce-service
  client:
    register-with-eureka: true #将自己注册到 Eureka-Server
    fetch-registry: true
    service-url:
      #表示将自己注册到哪个 eureka-server
      #这里为了方便,使用 Eureka Server的单机环境测试
      defaultZone: http://eureka9001.com:9001/eureka