server:
  port: 9001

eureka:
  instance:
    hostname: eureka9001.com # 服务实例名
  client:
    # 配置不向注册中心注册自己
    register-with-eureka: false
    # 表示自己就是注册中心，作用就是维护注册服务实例，不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与 eureka server 交互模块，查询服务和注册服务都需要依赖这个地址
      # defaultZone: http://localhost:9001/eureka
      # 相互注册
      defaultZone: http://eureka9002.com:9002/eureka
#  server:
#    # 禁止自我保护模式
#    enable-self-preservation: false
#    # 设置超时时间为 2s，在 2s内，收不到心跳，就认为是超时
#    eviction-interval-timer-in-ms: 2000