server:
  port: 10002

spring:
  application:
    name: member-service-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud_DB
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml # 指定 mapper.xml文件位置
  type-aliases-package: com.springcloud.entity # 实例类所在的包，这样通过类名可以引用

# 配置 eureka client
eureka:
  client:
    register-with-eureka: true # 将自己注册到 Eureka Server
    # 表示从 Eureka Server 抓取注册信息
    # 如果是单节点，是可以配置的，但是如果是一个集群，则必须配置 true
    # 才能配合 Ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      # 表示将自己注册到哪个 Eureka Server
      # defaultZone: http://localhost:9001/eureka
      # 这里将本微服务注册到 Eureka Server 集群，使用逗号间隔
      defaultZone: http://eureka9001.com:9001/eureka, http://eureka9002.com:9002/eureka
#  instance:
#    # 客户端向服务端发送心跳的时间间隔 1s（默认是 30s）
#    lease-renewal-interval-in-seconds: 1
#    # 服务端收到最后一次心跳后等待的时间上限
#    # 时间单位（秒），默认是 90s，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2